import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1698959800160 implements MigrationInterface {
    name = 'Initial1698959800160'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."item_item_type_enum" AS ENUM('Episode', 'Movie', 'MusicVideo', 'Season', 'Series', 'Video')`);
        await queryRunner.query(`CREATE TYPE "public"."item_provider_type_enum" AS ENUM('Imdb', 'Tmdb', 'Tvdb', 'Unknown')`);
        await queryRunner.query(`CREATE TABLE "item" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "item_type" "public"."item_item_type_enum" NOT NULL DEFAULT 'Video', "provider_type" "public"."item_provider_type_enum" NOT NULL DEFAULT 'Unknown', "provider_id" character varying(20) NOT NULL, "display_name" character varying(100), "item_slug" character varying(100), "path" character varying(2048) NOT NULL, CONSTRAINT "UQ_ce922804d0e98546c0af53cdb5c" UNIQUE ("item_slug"), CONSTRAINT "PK_eb3fcd003ddc6f23c342885677b" PRIMARY KEY ("uuid")); COMMENT ON COLUMN "item"."uuid" IS 'Unique Identifier for the record'; COMMENT ON COLUMN "item"."created_at" IS 'UTC timestamp, when record was created'; COMMENT ON COLUMN "item"."updated_at" IS 'UTC timestamp, when record was updated'; COMMENT ON COLUMN "item"."deleted_at" IS 'UTC timestamp, when record was soft-deleted'; COMMENT ON COLUMN "item"."item_type" IS 'Type Identifier for the Item'; COMMENT ON COLUMN "item"."provider_type" IS 'Provider Type Identifier, where the item information is taken from'; COMMENT ON COLUMN "item"."provider_id" IS 'Value points to a record from the Provider Type, where the item information is taken from'; COMMENT ON COLUMN "item"."display_name" IS 'Display value of the Item (e.g. a film title)'; COMMENT ON COLUMN "item"."item_slug" IS 'Slugified display name and/or file path information'; COMMENT ON COLUMN "item"."path" IS 'File path, where the item is stored'`);
        await queryRunner.query(`CREATE TYPE "public"."user_user_role_enum" AS ENUM('admin', 'user')`);
        await queryRunner.query(`CREATE TABLE "user" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" character varying(50) NOT NULL, "user_name" character varying(100), "password" character varying(32) NOT NULL, "user_role" "public"."user_user_role_enum" NOT NULL DEFAULT 'user', CONSTRAINT "UQ_758b8ce7c18b9d347461b30228d" UNIQUE ("user_id"), CONSTRAINT "PK_a95e949168be7b7ece1a2382fed" PRIMARY KEY ("uuid")); COMMENT ON COLUMN "user"."uuid" IS 'Unique Identifier for the record'; COMMENT ON COLUMN "user"."created_at" IS 'UTC timestamp, when record was created'; COMMENT ON COLUMN "user"."updated_at" IS 'UTC timestamp, when record was updated'; COMMENT ON COLUMN "user"."deleted_at" IS 'UTC timestamp, when record was soft-deleted'; COMMENT ON COLUMN "user"."user_id" IS 'Unique user name'; COMMENT ON COLUMN "user"."user_name" IS 'Display Name of a user'; COMMENT ON COLUMN "user"."password" IS 'encrypted password of a user'; COMMENT ON COLUMN "user"."user_role" IS 'User Role Identifier'`);
        await queryRunner.query(`CREATE TABLE "userinstance" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "user_id_from_emby_db" character varying(32) NOT NULL, "active" boolean NOT NULL DEFAULT false, "userId" uuid, "serverinstanceId" uuid, CONSTRAINT "UQ_0bf259f4c31c17dd6df2319969a" UNIQUE ("user_id_from_emby_db"), CONSTRAINT "PK_b7235ba574d3eea5e4663ff3941" PRIMARY KEY ("uuid")); COMMENT ON COLUMN "userinstance"."uuid" IS 'Unique Identifier for the record'; COMMENT ON COLUMN "userinstance"."created_at" IS 'UTC timestamp, when record was created'; COMMENT ON COLUMN "userinstance"."updated_at" IS 'UTC timestamp, when record was updated'; COMMENT ON COLUMN "userinstance"."deleted_at" IS 'UTC timestamp, when record was soft-deleted'; COMMENT ON COLUMN "userinstance"."user_id_from_emby_db" IS 'Identifier as stored in the Emby DB assigned to the Server'; COMMENT ON COLUMN "userinstance"."active" IS 'This user is still relevant and managed'; COMMENT ON COLUMN "userinstance"."userId" IS 'Unique Identifier for the record'; COMMENT ON COLUMN "userinstance"."serverinstanceId" IS 'Unique Identifier for the record'`);
        await queryRunner.query(`CREATE TABLE "watchedinstance" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "watched" boolean NOT NULL DEFAULT false, "last_watched_at" TIMESTAMP, "userinstanceId" uuid, "iteminstanceId" uuid, CONSTRAINT "PK_4c4cf9737828f4454063f43a680" PRIMARY KEY ("uuid")); COMMENT ON COLUMN "watchedinstance"."uuid" IS 'Unique Identifier for the record'; COMMENT ON COLUMN "watchedinstance"."created_at" IS 'UTC timestamp, when record was created'; COMMENT ON COLUMN "watchedinstance"."updated_at" IS 'UTC timestamp, when record was updated'; COMMENT ON COLUMN "watchedinstance"."deleted_at" IS 'UTC timestamp, when record was soft-deleted'; COMMENT ON COLUMN "watchedinstance"."watched" IS 'The item has been watched by the user on the referenced server instance'; COMMENT ON COLUMN "watchedinstance"."last_watched_at" IS 'UTC timestamp, when the user watched the item the last time'; COMMENT ON COLUMN "watchedinstance"."userinstanceId" IS 'Unique Identifier for the record'; COMMENT ON COLUMN "watchedinstance"."iteminstanceId" IS 'Unique Identifier for the record'`);
        await queryRunner.query(`CREATE TABLE "iteminstance" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "item_id_from_emby_db" character varying(32) NOT NULL, "itemId" uuid, "serverinstanceId" uuid, CONSTRAINT "UQ_4ec68b935f25e4e5685bd8fbd85" UNIQUE ("item_id_from_emby_db"), CONSTRAINT "PK_b513166edbbaf9c629e766f85ca" PRIMARY KEY ("uuid")); COMMENT ON COLUMN "iteminstance"."uuid" IS 'Unique Identifier for the record'; COMMENT ON COLUMN "iteminstance"."created_at" IS 'UTC timestamp, when record was created'; COMMENT ON COLUMN "iteminstance"."updated_at" IS 'UTC timestamp, when record was updated'; COMMENT ON COLUMN "iteminstance"."deleted_at" IS 'UTC timestamp, when record was soft-deleted'; COMMENT ON COLUMN "iteminstance"."item_id_from_emby_db" IS 'Identifier as stored in the Emby DB assigned to the Server'; COMMENT ON COLUMN "iteminstance"."itemId" IS 'Unique Identifier for the record'; COMMENT ON COLUMN "iteminstance"."serverinstanceId" IS 'Unique Identifier for the record'`);
        await queryRunner.query(`CREATE TABLE "serverinstance" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "server_id_from_emby_db" character varying(32) NOT NULL, "active" boolean NOT NULL DEFAULT false, "serverId" uuid, CONSTRAINT "UQ_f9ccbae211f1dddeb062f7854f1" UNIQUE ("server_id_from_emby_db"), CONSTRAINT "PK_a13942155a7e9d38d82e2d8a63c" PRIMARY KEY ("uuid")); COMMENT ON COLUMN "serverinstance"."uuid" IS 'Unique Identifier for the record'; COMMENT ON COLUMN "serverinstance"."created_at" IS 'UTC timestamp, when record was created'; COMMENT ON COLUMN "serverinstance"."updated_at" IS 'UTC timestamp, when record was updated'; COMMENT ON COLUMN "serverinstance"."deleted_at" IS 'UTC timestamp, when record was soft-deleted'; COMMENT ON COLUMN "serverinstance"."server_id_from_emby_db" IS 'Identifier of the Emby Server taken from the concrete installation'; COMMENT ON COLUMN "serverinstance"."active" IS 'This server is still relevant and managed'; COMMENT ON COLUMN "serverinstance"."serverId" IS 'Unique Identifier for the record'`);
        await queryRunner.query(`CREATE TABLE "server" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying(50) NOT NULL, "description" character varying(100), "main_server" boolean NOT NULL DEFAULT false, "api_key" character varying(32), "ip" inet, "port" smallint, CONSTRAINT "UQ_e16254733ff2264f94f856316ee" UNIQUE ("name"), CONSTRAINT "PK_a08f00d33ff9a73bd08a2edaae5" PRIMARY KEY ("uuid")); COMMENT ON COLUMN "server"."uuid" IS 'Unique Identifier for the record'; COMMENT ON COLUMN "server"."created_at" IS 'UTC timestamp, when record was created'; COMMENT ON COLUMN "server"."updated_at" IS 'UTC timestamp, when record was updated'; COMMENT ON COLUMN "server"."deleted_at" IS 'UTC timestamp, when record was soft-deleted'; COMMENT ON COLUMN "server"."name" IS 'Unique server name'; COMMENT ON COLUMN "server"."description" IS 'Description or remarks for the server'; COMMENT ON COLUMN "server"."main_server" IS 'This server is the one with the truth'; COMMENT ON COLUMN "server"."api_key" IS 'API Key of the Emby server required for REST API access'; COMMENT ON COLUMN "server"."ip" IS 'IP Address of the server - used for REST API access'; COMMENT ON COLUMN "server"."port" IS 'Port number of the server - used for REST API access'`);
        await queryRunner.query(`ALTER TABLE "userinstance" ADD CONSTRAINT "FK_f72e953878ac67846d4d1ada1a1" FOREIGN KEY ("userId") REFERENCES "user"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userinstance" ADD CONSTRAINT "FK_0a32bb35d6555a5a1e046ee7945" FOREIGN KEY ("serverinstanceId") REFERENCES "serverinstance"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "watchedinstance" ADD CONSTRAINT "FK_d1fe989f0b466d884a7be9f79bd" FOREIGN KEY ("userinstanceId") REFERENCES "userinstance"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "watchedinstance" ADD CONSTRAINT "FK_04d3cbe805ee96d97dac849eb9c" FOREIGN KEY ("iteminstanceId") REFERENCES "iteminstance"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iteminstance" ADD CONSTRAINT "FK_ba6c7942da895acf46b6c8b2070" FOREIGN KEY ("itemId") REFERENCES "item"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iteminstance" ADD CONSTRAINT "FK_8c46831732446b40d4f39fe761c" FOREIGN KEY ("serverinstanceId") REFERENCES "serverinstance"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "serverinstance" ADD CONSTRAINT "FK_4f523d6188f213b2a260c08bbd0" FOREIGN KEY ("serverId") REFERENCES "server"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "serverinstance" DROP CONSTRAINT "FK_4f523d6188f213b2a260c08bbd0"`);
        await queryRunner.query(`ALTER TABLE "iteminstance" DROP CONSTRAINT "FK_8c46831732446b40d4f39fe761c"`);
        await queryRunner.query(`ALTER TABLE "iteminstance" DROP CONSTRAINT "FK_ba6c7942da895acf46b6c8b2070"`);
        await queryRunner.query(`ALTER TABLE "watchedinstance" DROP CONSTRAINT "FK_04d3cbe805ee96d97dac849eb9c"`);
        await queryRunner.query(`ALTER TABLE "watchedinstance" DROP CONSTRAINT "FK_d1fe989f0b466d884a7be9f79bd"`);
        await queryRunner.query(`ALTER TABLE "userinstance" DROP CONSTRAINT "FK_0a32bb35d6555a5a1e046ee7945"`);
        await queryRunner.query(`ALTER TABLE "userinstance" DROP CONSTRAINT "FK_f72e953878ac67846d4d1ada1a1"`);
        await queryRunner.query(`DROP TABLE "server"`);
        await queryRunner.query(`DROP TABLE "serverinstance"`);
        await queryRunner.query(`DROP TABLE "iteminstance"`);
        await queryRunner.query(`DROP TABLE "watchedinstance"`);
        await queryRunner.query(`DROP TABLE "userinstance"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_user_role_enum"`);
        await queryRunner.query(`DROP TABLE "item"`);
        await queryRunner.query(`DROP TYPE "public"."item_provider_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."item_item_type_enum"`);
    }

}
