name: 'Publish changes to DockerHub'

description: 'Create a new docker image and sync README.md in that docker repository'

inputs:
  docker-file:
    description: 'The path to the Dockerfile in the repository used to create the new docker image'
    required: true
  docker-hub-password:
    description: 'The login password for DockerHub'
    required: true
  docker-hub-repository:
    description: 'The repository name of the provided login user will be merged to DockerHub slug value'
    required: true
  docker-hub-username:
    description: 'The login user name for DockerHub'
    required: true
  need-new-image:
    description: 'The value identifies, if a new docker image has to be published'
    required: true
  need-sync-readme:
    description: 'The value identifies, if the provided README.md file has to be published'
    required: true
  readme-file:
    description: 'The path to the `README.md`-file in the repository to be published'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Publish new docker image to DockerHub'
      uses: elgohr/Publish-Docker-Github-Action@v5
      if: inputs.need-new-image == 'true'
      env:
        DOCKERHUB_SLUG: ${{ inputs.docker-hub-username }}/${{ inputs.docker-hub-repository }}
        DOCKERFILE: ${{ inputs.docker-file }}
        DOCKERHUB_USERNAME: ${{ inputs.docker-hub-username }}
        DOCKERHUB_PASSWORD: ${{ inputs.docker-hub-password }}
      with:
        dockerfile: ${{ env.DOCKERFILE }}
        name: ${{ env.DOCKERHUB_SLUG }}
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - name: 'Publish a `README.md`-file to the DockerHub repository'
      uses: meeDamian/sync-readme@v1.0.6
      if: inputs.need-sync-readme == 'true'
      env:
        DOCKERHUB_SLUG: ${{ inputs.docker-hub-username }}/${{ inputs.docker-hub-repository }}
        README_FILE: ${{ inputs.readme-file }}
        DOCKERHUB_USERNAME: ${{ inputs.docker-hub-username }}
        DOCKERHUB_PASSWORD: ${{ inputs.docker-hub-password }}
      with:
        readme: ${{ env.README_FILE }}
        slug: ${{ env.DOCKERHUB_SLUG }}
        user: ${{ env.DOCKERHUB_USERNAME }}
        pass: ${{ env.DOCKERHUB_PASSWORD }}
