version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/apps/**/Dockerfile'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 3
    target-branch: 'main'
    labels:
      - 'dependencies'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 3
    target-branch: 'main'
    labels:
      - 'dependencies'

  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    target-branch: 'main'
    labels:
      - 'dependencies'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 5
    target-branch: 'main'
    labels:
      - 'dependencies'
    groups:
      angular:
        patterns:
          - '@angular*'
        update-types:
          - 'minor'
          - 'patch'
      nx:
        patterns:
          - '@nx*'
          - 'nx*'
        update-types:
          - 'minor'
          - 'patch'
      sap-fundamentals:
        patterns:
          - '@fundamental-ngx*'
          - '@sap-theming*'
          - 'fundamental-styles'
        update-types:
          - 'minor'
          - 'patch'
      secretlint:
        patterns:
          - '@secretlint*'
          - 'secretlint'
        update-types:
          - 'minor'
          - 'patch'
