version: '3.9'

name: edc-db-dev
services:
  db:
    container_name: db
    hostname: postgresql
    image: 'postgres:${POSTGRES_VERSION}'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=${DATABASE_NAME}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'POSTGRES_USER=${DATABASE_USERNAME}'
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
    networks:
      - services

  dbadmin:
    container_name: dbadmin
    hostname: postgresql-admin
    image: 'dpage/pgadmin4:${PGADMIN_VERSION}'
    depends_on:
      - db
    ports:
      - '5433:80'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}'
    volumes:
      - './tools/servers_pgadmin_dev.json:/pgadmin4/servers.json'
      - 'dbadmin:/var/lib/pgadmin'
    networks:
      - services

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      device: '$PWD/../../../Docker_Content/edc/db'
      o: bind

  dbadmin:
    driver: local
    driver_opts:
      type: none
      device: '$PWD/../../../Docker_Content/edc/dbadmin'
      o: bind

networks:
  services:
    name: 'emby-data-check'
