name: edc-db-dev
services:
  db:
    container_name: db
    hostname: postgresql
    image: 'postgres:${POSTGRES_VERSION}'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=${DATABASE_NAME}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'POSTGRES_USER=${DATABASE_USERNAME}'
    networks:
      - services

  dbadmin:
    container_name: dbadmin
    hostname: postgresql-admin
    image: 'dpage/pgadmin4:${PGADMIN_VERSION}'
    depends_on:
      - db
    ports:
      - '5433:80'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}'
    volumes:
      - './tools/pgadmin/servers_pgadmin_dev.json:/pgadmin4/servers.json'
    networks:
      - services

  mockoon-mock:
    container_name: mockoon
    hostname: mockoon
    image: mockoon/cli
    command: ['--data', './emby.server.json']
    ports:
      - '8096:8096'
    volumes:
      - ./tools/mockoon/emby.server.json:/emby.server.json:ro
    networks:
      - services

networks:
  services:
    name: 'emby-data-check'
