name: 'Prepare Workflow context values'

description: 'Fetch context values for the currently running workflow'

inputs:
  main-branch-name:
    description: 'The name of the main branch in your repo, used as the target of PRs - usually `main` or `master`'
    default: 'main'

outputs:
  base:
    description: 'The value is the base commit id required by subsequent `nx affected` commands'
    value: ${{ steps.get-shas.outputs.base }}
  head:
    description: 'The value is the head commit id required by subsequent `nx affected` commands'
    value: ${{ steps.get-shas.outputs.head }}
  is-merge:
    description: 'The value identifies, if it is a merge request into provided input `main-branch-name`'
    value: ${{ steps.is-merge.outputs.is-merge }}
  is-pr:
    description: 'The value identifies, if it is a pull request'
    value: ${{ steps.is-pr.outputs.is-pr }}

runs:
  using: 'composite'
  steps:
    - name: 'Derive appropriate SHAs'
      id: get-shas
      uses: nrwl/nx-set-shas@v3
      env:
        MAIN_BRANCH_NAME: ${{ inputs.main-branch-name }}
      with:
        main-branch-name: ${{ env.MAIN_BRANCH_NAME }}
        set-environment-variables-for-job: false

    - name: 'Is it a `Merge`-request?'
      id: is-merge
      shell: bash
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        MAIN_BRANCH_NAME: ${{ inputs.main-branch-name }}
      run: |
        echo "is-merge=${{ env.GITHUB_EVENT_NAME == 'push' && env.GITHUB_REF_NAME == env.MAIN_BRANCH_NAME }}" >> $GITHUB_OUTPUT

    - name: 'Is it a `Pull`-request?'
      id: is-pr
      shell: bash
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
      run: |
        echo "is-pr=${{ env.GITHUB_EVENT_NAME == 'pull_request' }}" >> $GITHUB_OUTPUT
