name: 'Change Detection in Nx Monorepo'

description: 'Detect affected apps and libs'

inputs:
  nx-project-name:
    description: 'The project name from Nx Workspace to be evaluated'
    required: true
  docker-readme-file:
    description: 'The path to `README.md`-file, which should be synced with DockerHub'
    required: true

outputs:
  need-new-image:
    description: 'The value identifies, if the image on DockerHub for the provided project needs to be updated'
    value: ${{ steps.need-new-image.outputs.need-new-image }}
  need-sync-readme:
    description: 'The value identifies, if the provided `README.md`-file for the image on DockerHub needs to be updated'
    value: ${{ steps.need-sync-readme.outputs.need-sync-readme }}

runs:
  using: 'composite'
  steps:
    - name: 'Find affected apps and projects'
      id: findAffectedFromNx
      shell: bash
      run: |
        echo "npx nx print-affected --base=${{ env.BASE }} --head=${{ env.HEAD }} --select=projects" >> $GITHUB_OUTPUT

    - name: 'Is a new image required?'
      id: need-new-image
      shell: bash
      env:
        LIST_OF_AFFECTED: ${{ steps.findAffectedFromNx.outputs.affected }}
        NX_PROJECT_NAME: ${{ inputs.nx-project-name }}
      run: |
        echo "need-new-image=${{ contains(env.LIST_OF_AFFECTED, env.NX_PROJECT_NAME) }}" >> $GITHUB_OUTPUT

    - name: 'Detect changes of specific files'
      uses: dorny/paths-filter@v2
      id: findAffectedFromFilter
      env:
        READMEFILE: ${{ inputs.docker-readme-file }}
      with:
        filters: |
          docker_readme:
            - added|modified: ${{ env.READMEFILE }}

    - name: 'Is a sync of `README.md`-file required?'
      id: need-sync-readme
      shell: bash
      run: |
        echo "need-sync-readme=${{ steps.findAffectedFromFilter.outputs.docker_readme == 'true' }}" >> $GITHUB_OUTPUT
