name: API Pipeline

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true

permissions:
  contents: read

jobs:
  test-api-unit:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: 'Set up Node.js environment'
        uses: ./.github/actions/setup-nodejs
        with:
          need-cache-npm: true
          need-cache-cypress: false

      - name: 'Run unit tests'
        run: npx nx test ${{ inputs.project }}
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      - name: 'Upload coverage artifacts'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: coverage-${{ inputs.project }}-unit
          path: coverage/apps/${{ inputs.project }}/
          retention-days: 3

  test-api-e2e:
    name: 'API E2E Tests'
    runs-on: ubuntu-latest
    env:
      API_PORT: 3000
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: 'Set up Node.js environment'
        uses: ./.github/actions/setup-nodejs
        with:
          need-cache-npm: true
          need-cache-cypress: false

      - name: 'Run API E2E tests'
        run: npx start-server-and-test 'npx nx serve ${{ inputs.project }} --configuration=production' "http://localhost:${API_PORT}/api" 'npx nx e2e ${{ inputs.project }}-e2e'
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      - name: 'Upload coverage artifacts'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: coverage-${{ inputs.project }}-e2e
          path: coverage/apps/${{ inputs.project }}-e2e/
          retention-days: 3
