name: Continuous Integration Pipeline

on:
  push:

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  workflow_dispatch:
    inputs:
      edc-api-manual:
        description: 'Is app [edc-api] affected?'
        required: false
        type: boolean
        default: false

      edc-ui-ng-manual:
        description: 'Is app [edc-ui-ng] affected?'
        required: false
        type: boolean
        default: false

permissions:
  actions: read
  attestations: read
  checks: read
  contents: read
  deployments: read
  id-token: none
  issues: write
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  static-checks:
    name: 'Static Code Checks'

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          fetch-depth: 0

      - name: 'Set up Node.js environment'
        uses: ./.github/actions/setup-nodejs
        with:
          need-cache-npm: true
          need-cache-cypress: false

      - name: 'Lint all projects'
        run: npm run lint:all:check
