name: Continuous Integration Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - gh-pages

permissions:
  actions: read
  attestations: read
  checks: read
  contents: read
  deployments: read
  id-token: none
  issues: write
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  build:
    name: 'Build'

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: 'Setup project-specific Node.js version'
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: 'Install dependencies (via npm)'
        shell: bash
        run: |
          npm install

      - name: 'Build all projects'
        run: npx nx run-many --parallel --target=build

  sonarcloud:
    name: 'Static code checks'

    runs-on: ubuntu-latest

    if: github.actor != 'dependabot[bot]'

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: 'Run static code checks on `sonarcloud.io`'
        uses: sonarsource/sonarcloud-github-action@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
